### ISSUE TITLE
close connections after some timeout of *no* real RPC 

### ISSUE THREAD

**Issue by senior7515** [smfrpc/smf#243]
# Basic Info

- [ x] operating system
Linux
- [ x] git hash
HEAD
- [ x ] compiler
gcc8

## Language

- [ x ] C++
- [ ] Go
- [ ] Java

## Iff C++
- [ x ] using dpdk 
- [ x ] using native TCP
- [ x ] epoll networking

Applies to all cpp

----

# Details
### Logs, core dumps, debugger logs, etc.
```
    #0 0x7f9d060f9e50 in calloc (/lib64/libasan.so.5+0xeee50)                                                                                                                                          #1 0x17c3716 in hdr_init ../src/third_party/HdrHistogram_c/src/hdr_histogram.c:334                                                                                                                 #2 0x6c5993 in smf::hist_t::hist_t() ../src/include/smf/histogram.h:24                                                                                                                        
    #3 0x6c5c7a in std::_MakeUniq<smf::hist_t>::__single_object std::make_unique<smf::hist_t>() /usr/include/c++/8/bits/unique_ptr.h:831                                                               #4 0x6c433d in smf::histogram::histogram() ../src/core/histogram.cc:27                                                                                                                             #5 0x6c4055 in smf::histogram::make_unique(hdr_histogram const*) ../src/core/histogram.cc:21                                                                                                       #6 0x538658 in smf::unique_histogram_adder::unique_histogram_adder() (/home/agallego/workspace/smf/build_debug/demo_apps/demo_server+0x538658)                                                     #7 0x4fa52b in operator() ../demo_apps/server/main.cc:56 
```
### How to reproduce. Be as detailed as you can.
on the demo apps if you have a poorly behaved client, and the client drops, and the kernel hasn't cleaned up the connection, and you Ctrl-C you core dump.

We need to close connections and clean up resources - histograms etc. for it.

**Comment by senior7515** [comment]
fixed in #284
